COMPILER = g++
FLAGS = -Wall

fig10_01: fig10_01.cpp 
	$(COMPILER) $(FLAGS) $< -o $@

fig10_05: fig10_05.cpp PhoneNumber.cpp
	$(COMPILER) $(FLAGS) PhoneNumber.cpp $< -o $@

fig10_08: fig10_08.cpp Date.cpp
	$(COMPILER) $(FLAGS) $< Date.cpp -o $@
